wireplumber.components = [
  {
    name = "90-bt-auto-switch.lua", type = script/lua
    provides = hooks.example.bt-auto-switch
  }
]

wireplumber.profiles = {
  main = {
    hooks.example.bt-auto-switch = required
  }
}
